### ISSUE TITLE
Wiki: Home, Feature List, Schema

### ISSUE THREAD

**Issue by paulobocanegra** [yanrivera19/Slick#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

---

# Feature List

- [x] Should have 7 Features.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [Feature/MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each feature
- [x] Correctly formatted
    - [x] features are listed in an ordered list
    - [x] Each feature is broken down into bullet points

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

---

**Comment by paulobocanegra** [comment]
Excelente home page! Solo falta el placeholder para el live link.

**Comment by paulobocanegra** [comment]
Dale un vistazo al Feature list, nos fuimos del 1 al 5 luego 6 5 6. 
Tenemos muchos Features, pasa Dashboard/Profile y Search/Browse a bonus. Mantén los bullet points.

**Comment by yanrivera19** [comment]
Ok gracias! Eso haré!

**Comment by paulobocanegra** [comment]
Schema:
 En `users`: los usuarios van a pertenecer a multiples workspace, en consecuencia, no deberíamos mantener 1 workspace_id. Yo lo removería totalmente, crea un join table `user_workspaces` que conecta users con workspaces.

**Comment by yanrivera19** [comment]
> Schema: En `users`: los usuarios van a pertenecer a multiples workspace, en consecuencia, no deberíamos mantener 1 workspace_id. Yo lo removería totalmente, crea un join table `user_workspaces` que conecta users con workspaces.

Ohh that makes a lot of sense! Lo arreglo

**Comment by paulobocanegra** [comment]
Excelente! 💯
